use strict;
use warnings;

use Test::More tests => 3;

use MIME::Base64 'decode_base64url';
use Digest::MD5 'md5_base64';

BEGIN {
    use_ok( 'Nick::Audio::MAD' );
};

my @data = map(
    decode_base64url( $_ ), qw(
        _-NAxAAnC_pMQ0NAATECf__1wMDeIlAABET3DpW7u_D2goiJuiSWLi59w9oKJIufi4ue-iJoif_KJy7u8C59oKCgokihki58EGSHAoZuLi77vpX6C4u8EBwDQwsBQFhhYdg3BueQAuH4wUMEMFYfiAADADh_ZAoKJIoYnCIkihm7vfD8In-7vwiJIoYnL37vf____73__v8f-7vwiI4oKMtCIgj3-Hn4ACoQSCMUCgZjMZjIZDIZjpjQWLxoA9eLPImTn5Gmzju_xlBGgDAwUg
        _-NCxCY0m8cCX4eiAqGx10VfAYZkFDEBJCEA-al_8T4geHSHpjJADJ32Tv_EnHJBuqFuhPoDxYGTNgNIwAkbeu-r-ACTAGXhaIAkWBmRoYhIqI6AxYwDLBgNAaBQ3UZM6rtY9_-AKDAKFhn4GJEgFCwTAhioGxwLXgYAEAwvoTYguIa9D_f__8UGXhyxpC4BYgxAIAA2Ph3AsUIiDdcUcDFBg90Gz4IgIGLRgasa9vQ80TdnWbq_85IVLz__G6uaGBwDJIfFjZgQ2BdHgEDDrLc
        _-NCxBcn8obABc9IAKP1usXkgLg2pk7gukhNkAoZkj8NnSBMVigMOb81FQDgQSAEFAEgmEzAISBDCFcVsVJoRBZGXPjxcuHZnJLG15kPg_Fp11d_-xjUfKSzUv_LZS288s8pLSltRyS6F1V27rx9JLpAzIaZsBWFAVBUBPsLHlNF8Fg6JZEjnRY9_gqCqwVLA0DT1nZ5jrXf_VDDKQyCxiIQBoZzb-NFqCEyAQLJcCzacYRmkhy1alNEWdraTIIgBJkAIlnt5VKKfdN91YgEEFw
        _-NCxDs1Q76cAt5Q-KBpzM6kKydxhi0GaF5iqIID0XnTdl11hy84qwBcgLcBhgq-DEkO66XvV4sIokwpgyXScyerWN14s80DyV7H4g9MFQZOllToPpCHsiroBAB4OIDQPA8UGg6T2Wy75nqpGTP__pdTM_UW_Jtf0xVjaH6kiCShwj44RR8wlDXh--P44jq5nuJG3uZZ8RZ-Z8Lp6R3q03KlmLeWRiAP_zWLhrnBI4NCEYQOGL5xelBJoROZBQKPNNoiQF6R8EIDKIxogHDpABw
        _-NCxCowg7agAspLiyoeIVJRrmbss50YVKnHpXlgukbK9u4tCIq8UiYvKnuXuny0tRFAWpurAgITpElphnqNACGacuVYojDIEgyBpSR0VNS0tO7y4TWbQ-NmQsAIUwEQaRPFUxSdPIzIuwnDZW4uAg4PvdTqpz59__6J-iuxSzREVQzqKh0kXFlISijxQT7LZtLpmqspRVhULETN9zfGIURZckLlEPWfyhLQOYGTGJXEoEFCDGszJFDasjPwhCuACsy7QCvzW2jPqCZMZlkAzgI
        _-NCxCwxw3KMBNYM1IiISaxa5N5aLiqZKpFrmcJHKjaUpkxd-lDn6jyAl1YmgspelGg6ZkICSzIGgdilgQCkX-Y--ityg0XjUeZdG3dj0uLQBRp-EkhS5fKJVv-nJb2eXn_zjzLT2o3K5tVpua5EAktIy89kqfPReXlLfv5z_-f-1Go43yt_-f_0-mkSPmCXOLmtdHPveZnMqfJsEtx2SNRkvGFjwlOtBbkje_dBH3LSAL2A0oUCKkQeGGg5SBxahOpElYw0IuQqslShJ8q1TI0
        _-NCxCkou3aYHsPQ03JELTKrUS3PXr5DtQLxziO050cphMj5ISS1wzCiM1_JvPDXzs48o456Zmvq1q4tZqV-NfmuuV_u4mpae4aUul5jqLVck0lIKDQnHXYx2aJqv__n__j_6447tYKD447k2pZjtuLnhttmaDmFqf__-XQLbSS0zjmpgrIqCctu2-awR8L_kO8T8pDeQtQokihMA4COGK28bW6w3d1McadldyrjvrkhqV3LXF3d7tEe5pCKSr0UXD8P6uPhK_eyxcOz3TIq45g
        _-NCxEomW5acHnsQl7KThEMRxd3l3d0_ivev6RObd3WTziCzjhYUUbN8r___31z4xE1V-S4h4DuQjKEETCiI03b1XEI9282e8w1KajoIyjDIMAHSU1e_rc-uTugVACm3_gWWOgFB8yuqOIESytKytCPjk-VWt_LnqTK86TRQ03SCnAEiJyiC9Mq6OV4zn6aS-QUgpStbU1H2WIQlDj6Wnk8eDetcYYZlFh0dDQ1291KGVJxPqRtsrbcsZ57dEkepUSrHwy-PlChhhIkMoVYa9kM
        _-NCxHQnfBaAHmPG8NvKP-Xs2y9i3Sz0MGdKr9_2ZoxXvnzKKpLrmj8PVBcI4l5ZWqHC3E-SDmoRztGrgXU1X5_GSmj_ENJYEaW4hywWJNusNbiwuldOSk4BNi5J84VcLKcR_JtDXhfkKnTsNuXYXp9N5cS3Hyu6g2SUFcsE6XZBVFQuRdUonmZpQ1-qavXsXFrQabCBiNROaEwwyMKzNc0SvX8vKYUTlY9m1w2VGolgKSrI51AqoO51H3yV1nFnkd3_lluoJQQDMw0uUJyOWSg
        _-NCxJojwmpEBHhHqOg4oNQh4huX5QyU-pi6jEl8tsra0FlSC4uLoHSCFKaNptSZIZknEliOAyTiS-YoS8ml4nNkl45im1z1MTkwjIa0QRoA0PI6sntLTnzW1a4SWRUdLdtnzTJG5XbZp5ytn_s89tf_t5bZ7_vJ2gFDJliVUJCTQCoUFBoNAqIlDzolGAy7CT9YCAolZ5IKu4_1VUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU
        _-NCxM8minn8BMMM2FVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU
        _-NCxPgAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU
    )
);

my @want_md5 = qw(
    UUwPR+P7ZvhnF6B28OK32A
    FnvJ1sjjvdzg1OC+qx1FRg
    CBzzTJxLM74ASQKgOTf/4g
    UgaylkIAFQcLsj6a6pH/kw
    Y+tIGz0Qd3TBVD8ShYGqyw
    AQ7SCa3iBFihb89x1AfuEg
    Ekfkvu20qonmBhvLmvWFsA
    1VPKA3uJk45iRvY+lbJS0w
    /i8RlLc2fu69c3AxjUrwDQ
    vaclAnRUZF5olf5fdNFrVQ
    J3+Qg5xB0y3u2f0XG9uMZA
    FdERTAJr9aCf4jU1jRsvpQ
);

my( $buff_in, $buff_out );
my $mad = Nick::Audio::MAD -> new(
    'buffer_in'     => \$buff_in,
    'buffer_out'    => \$buff_out,
    'gain'          => -3,
    'debug'         => 1
);

ok( defined( $mad ), 'new()' );

my @got_md5;
while ( @data ) {
    $buff_in .= shift @data;
    $mad -> decode()
        and push @got_md5 => md5_base64( $buff_out );
}
$mad -> decode( 1 )
    and push @got_md5 => md5_base64( $buff_out );

is_deeply( \@got_md5, \@want_md5, 'decode()' );
